#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'dsb'

client = Dsb::Client.new(File.join('config', 'connection.yml'))

daemon = Dsb::{{klass}}.new(:client => client, :stdout => STDOUT)
daemon.run
